feat: set $parent on create and set
bpmn-io/moddle pull request #50
Opened 2023-02-03 09:52 UTC by philippfromme

This pull request implements a simple approach to maintaining the `$parent` property.

## What it does ✅ 

### Sets `$parent` when using `Moddle#create`

```javscript
var complexNesting = model.create('props:ComplexNesting', {
  nested: model.create('props:Complex')
});

console.log(complexNesting.get('nested').$parent); ✅ 
```

### Sets `$parent` when using `Base#set`

```javascript
var complexNesting = model.create('props:ComplexNesting'),
    nested = model.create('props:Complex');

complexNesting.set('nested', nested);

console.log(nested.$parent); ✅ 
```

## What it doesn't do ⛔

## Setting parent without using API

```javascript
var complexNesting = model.create('props:ComplexNesting'),
    nested = model.create('props:Complex');

complexNesting.nested = nested;

console.log(nested.$parent); ⛔ 
```

## Unsetting parent

```javascript
var complexNesting = model.create('props:ComplexNesting'),
    nested = model.create('props:Complex');

complexNesting.set('nested', nested);

complexNesting.nested = undefined;

console.log(nested.$parent); ⛔ 
```

This is the approach I'd prefer. Every model element has a clearly defined API. Using this API is the preferred way of working with model elements. Accessing properties without using the API (`complexNesting.nested = nested;`) is possible but not necessarily intended. I consider setting and unsettling the parent using proxies as magic and, therefore, wouldn't implement that.

---

Closes #41

2023-02-03 09:54 UTC, philippfromme commented
@barmac @marstamm @nikku @smbea, feel free to have a look and share your sentiment regarding my proposal.

2023-02-03 10:12 UTC, nikku commented
> I consider setting and unsettling the parent using proxies as magic and, therefore, wouldn't implement that.

Not sure from this comment: Did you consider proxies? I'd love us to consider them, and discard if we found them unsuitable.

> Unsetting parent

I think we cannot ship without that. If `$parent` is managed by the infrastructure _then_ I'd assume that unsetting (via a well known path) does unset `$parent`, too. We'll otherwise not have a way to find out if an element is attached to the tree.

2023-02-03 10:43 UTC, philippfromme commented
> Not sure from this comment: Did you consider proxies? I'd love us to consider them, and discard if we found them unsuitable.

I wanted to start the conversation first. I was anticipating the question about proxies. I'm not to fond of them. I agree that it's not great to set the `$parent` but not have any way of unsetting it. Maybe a `Base#unset` method is missing.

2023-02-03 10:44 UTC, nikku commented
> Maybe a `Base#unset` method is missing.

Usually we set to `undefined` instead. But `Base#unset` would be valid, too. We'd just need to make sure there exists a way to properly unset, too.

2023-02-03 10:51 UTC, philippfromme commented
> Usually we set to `undefined` instead.

Now that I'm thinking about it, this could actually work. When calling `set` with `undefined` we unset `$parent` of all existing properties before removing them. I'll try that out.

2023-02-06 08:52 UTC, philippfromme commented
> I'll try that out.

Done.

2023-02-06 11:52 UTC, nikku commented
@philippfromme Did you try this against diagram-js / bpmn-moddle / bpmn-js? Great code-bases to integration-test against.

2023-02-06 13:20 UTC, philippfromme commented
> @philippfromme Did you try this against diagram-js / bpmn-moddle / bpmn-js? Great code-bases to integration-test against.

No I haven't done that yet. I can do that, though. I assume that introducing this feature would allow us to remove a lot of `child.$parent = parent` across our libraries.

2023-02-09 16:02 UTC, barmac requested changes
Let's verify that it does not break anything in the downstream libraries.

2023-02-10 15:24 UTC, philippfromme commented
> Let's verify that it does not break anything in the downstream libraries.

That's what I'm doing.

2023-02-14 12:01 UTC, philippfromme commented
I will pick this up again once I have time.

2023-02-17 14:43 UTC, marstamm commented
> I will pick this up again once I have time.

I converted the PR to draft for now so we don't get notification on Slack about it

2026-05-13 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/bpmn-io/moddle?pullRequest=50) <br/>All committers have signed the CLA.

2026-07-14 13:24 UTC, philippfromme commented
Closing this for now as I won't have time to work on this anytime soon.

2026-07-14 13:24 UTC, closed without merging